// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIyjQvljZdnTVjmnffTfejntHK-_uzbQ',
    appId: '1:868463876797:web:c381bab4913fa619fc75d4',
    messagingSenderId: '868463876797',
    projectId: 'family-budget-ae861',
    authDomain: 'family-budget-ae861.firebaseapp.com',
    storageBucket: 'family-budget-ae861.firebasestorage.app',
    measurementId: 'G-MJ6YQ4J64D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV28p-WEGT2rlaKyMKvS_940dFWqZxcWM',
    appId: '1:868463876797:android:aecff427e4d6ef9ffc75d4',
    messagingSenderId: '868463876797',
    projectId: 'family-budget-ae861',
    storageBucket: 'family-budget-ae861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0Tz93uwK8Yog_-oRjB3_eToCSJD-tuI',
    appId: '1:868463876797:ios:9dac6243e72f0b35fc75d4',
    messagingSenderId: '868463876797',
    projectId: 'family-budget-ae861',
    storageBucket: 'family-budget-ae861.firebasestorage.app',
    iosBundleId: 'familyBudget.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0Tz93uwK8Yog_-oRjB3_eToCSJD-tuI',
    appId: '1:868463876797:ios:9adaca76b81687c6fc75d4',
    messagingSenderId: '868463876797',
    projectId: 'family-budget-ae861',
    storageBucket: 'family-budget-ae861.firebasestorage.app',
    iosBundleId: 'com.example.familyBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcIyjQvljZdnTVjmnffTfejntHK-_uzbQ',
    appId: '1:868463876797:web:c0e1d32b69a22ac3fc75d4',
    messagingSenderId: '868463876797',
    projectId: 'family-budget-ae861',
    authDomain: 'family-budget-ae861.firebaseapp.com',
    storageBucket: 'family-budget-ae861.firebasestorage.app',
    measurementId: 'G-WKWVWLBP8L',
  );

}